"use client";
import { motion } from "framer-motion";
import Image from "next/image";

const pieces = [
  {
    image: "/jewelry/studs.jpg",
    alt: "Amipi GIA-certified diamond stud earrings",
    title: "Everyday Brilliance, 0.50ctw GIA Diamond Studs",
    description:
      "Clean four-prong stud earrings set with a matched pair of round brilliant diamonds, GIA-certified. The kind of piece you put on once and forget you're wearing.",
    tags: ["diamond studs", "0.50ctw", "GIA certified", "everyday"],
    tone: "Amipi Style",
  },
  {
    image: "/jewelry/ring-solitaire.png",
    alt: "Amipi platinum solitaire engagement ring with GIA diamond",
    title: "One Stone. One Question. Forever.",
    description:
      "A platinum solitaire built for the moment that matters. GIA-graded center stone, knife-edge shank, hand-finished in NYC.",
    tags: ["engagement ring", "solitaire", "platinum", "bridal"],
    tone: "Luxury",
  },
  {
    image: "/jewelry/bracelet.jpg",
    alt: "Amipi diamond tennis bracelet",
    title: "The Tennis Bracelet, Reimagined for Every Wrist",
    description:
      "Claw-set round brilliants in a continuous line. Safety-locked, diamond-balanced, and comfortable enough to sleep in.",
    tags: ["tennis bracelet", "diamond", "safety lock"],
    tone: "Minimalist",
  },
  {
    image: "/jewelry/earrings-hoop.jpg",
    alt: "Amipi diamond in-and-out hoop earrings",
    title: "U-Shaped In-and-Out Diamond Hoops",
    description:
      "Shared-prong hoops set inside and out so they catch light from every angle. GIA-graded VS diamonds, safety lock closure for all-day wear.",
    tags: ["hoop earrings", "in-and-out", "diamond hoops"],
    tone: "Professional",
  },
];

export default function ProductGallery() {
  return (
    <section id="gallery" className="bg-cream-50 py-20">
      <div className="max-w-7xl mx-auto px-6">
        <div className="text-center mb-14">
          <span className="text-xs font-bold uppercase tracking-widest text-gold-600">Proof In The Product</span>
          <h2 className="text-3xl md:text-4xl font-black text-navy-700 mt-2 leading-tight">
            Real Amipi pieces, real GemCopy descriptions
          </h2>
          <p className="text-gray-500 text-sm md:text-base mt-3 max-w-2xl mx-auto">
            Every description below was generated by GemCopy from the piece's GIA certificate data. No human rewriting.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {pieces.map((piece, i) => (
            <motion.article
              key={piece.title}
              initial={{ opacity: 0, y: 28 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-40px" }}
              transition={{ duration: 0.55, delay: i * 0.08 }}
              className="group bg-white rounded-2xl overflow-hidden border border-gray-100 hover:border-gold-300 hover:shadow-xl hover:shadow-gold-100/40 transition-all"
            >
              <div className="grid grid-cols-5">
                <div className="col-span-2 relative aspect-square bg-navy-50">
                  <Image
                    src={piece.image}
                    alt={piece.alt}
                    fill
                    sizes="(max-width: 768px) 40vw, 25vw"
                    className="object-cover group-hover:scale-105 transition-transform duration-700"
                  />
                </div>
                <div className="col-span-3 p-5 flex flex-col">
                  <span className="text-[10px] font-bold uppercase tracking-widest text-gold-600 mb-1.5">
                    Tone: {piece.tone}
                  </span>
                  <h3 className="font-black text-navy-700 text-base leading-snug mb-2">
                    {piece.title}
                  </h3>
                  <p className="text-xs text-gray-600 leading-relaxed mb-3 flex-1">
                    {piece.description}
                  </p>
                  <div className="flex flex-wrap gap-1">
                    {piece.tags.map((tag) => (
                      <span
                        key={tag}
                        className="text-[10px] bg-navy-50 text-navy-600 border border-navy-100 px-2 py-0.5 rounded-full"
                      >
                        {tag}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            </motion.article>
          ))}
        </div>
      </div>
    </section>
  );
}
